amplypix/amplypix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', include('client.urls')),   
    path('photographer/', include('photographer.urls')),


    path('modrator/', include('modrator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amplypix/client/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.views import LoginView

app_name = "client"

urlpatterns = [
    

    #index / login
    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),
    # Index Redirect Client / Photographer
    path('index', index, name='index'),


    # Complete Profile
    path('complete_profile_client', complete_profile_client, name='complete_profile_client'),
    # Dashboard Client
    path('update_profile', update_profile, name='update_profile'),
    # Profile Client
    url(r'^profile_client/(?P<username>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', profile_client, name='profile_client'),
    # Update Profile Client
    path('dashboard_client', dashboard_client, name='dashboard_client'),
    # Post Task
    path('post_task', post_task, name='post_task'),
    # Edit Task
    url(r'^edit_task/(?P<id>\d+)/$', edit_task, name='edit_task'),
    # List Task 
    path('list_task', list_task, name='list_task'),

    url(
        r'^location-autocomplete/$',
        LocationAutocomplete.as_view(),
        name='location-autocomplete',
    ),


    url(
        r'^languague-autocomplete/$',
        LanguagueAutocomplete.as_view(),
        name='languague-autocomplete',
    ),


] 

amplypix/photographer/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from . import views
from .views import *

app_name = "photographer"

urlpatterns = [
    
    # complete profile photographer
    path('complete_profile_photographer', complete_profile_photographer, name='complete_profile_photographer'),

    # briefcase  
    path('complete_profile_briefcase', complete_profile_briefcase, name='complete_profile_briefcase'),
    # Dashboard Photographer
    path('dashboard_photographer', dashboard_photographer, name='dashboard_photographer'),
    # Update Profile
    path('update_profile_photographer', update_profile_photographer, name='update_profile_photographer'),
    # Profile 
    url(r'^profile_photographer/(?P<username>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', profile_photographer, name='profile_photographer'),
    # Update Briefcase
    path('update_briefcase', update_briefcase, name='update_briefcase'),
] 

amplypix/photographer/models.py
from django.db import models
from modrator.models import User, Location, Languague
from client.validators import validate_file_size
from client.categories import *


class PhotographerAP(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    public_bio = models.CharField(max_length=150, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='client/profile/avatar/%Y/%m/%d', default='client/profile/default.jpg', null=True, blank=True, validators=[validate_file_size])
    
    
    city = models.ForeignKey(Location, on_delete=models.CASCADE, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    language = models.ManyToManyField(Languague, blank=True)

    is_active = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    #WEBSITES & SOCIAL CHANNEL
    youtube = models.CharField(max_length=50, blank=True, null=True)
    instagram = models.CharField(max_length=60, blank=True, null=True)
    tiktok = models.CharField(max_length=60, blank=True, null=True)

    def validate_briefcase(self):
        s = Briefcase.objects.get(user=self)
        return str(s)

class Briefcase(models.Model):

    user = models.OneToOneField(PhotographerAP, on_delete=models.CASCADE, primary_key=True)
    photo_1 = models.ImageField(upload_to='client/profile/briefcase/%Y/%m/%d', validators=[validate_file_size])
    photo_2 = models.ImageField(upload_to='client/profile/briefcase/%Y/%m/%d', validators=[validate_file_size])
    photo_3 = models.ImageField(upload_to='client/profile/briefcase/%Y/%m/%d', validators=[validate_file_size])
    photo_4 = models.ImageField(upload_to='client/profile/briefcase/%Y/%m/%d', validators=[validate_file_size])
    photo_5 = models.ImageField(upload_to='client/profile/briefcase/%Y/%m/%d', validators=[validate_file_size])
    video_url = models.CharField(max_length=150, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

amplypix/photographer/forms.py
from .models import *
from django import forms
from django.conf import settings
import datetime
from datetime import datetime, time, date, timedelta
from dal import autocomplete

min_date = date.today() - timedelta(50*365)
today = date.today() - timedelta(18*365)

class PhotographerAPForm(forms.ModelForm):

    birth_date = forms.DateField(widget=forms.DateTimeInput(format=('%Y-%m-%d'), attrs={'class':'form-control datepicker', 'min':min_date ,'max': today, 'value': today,  'type':'date' } ), 
                      )

    class Meta:
        model = PhotographerAP
        fields = '__all__'
        exclude = ['user', 'is_active']


        widgets = {
            'language' : autocomplete.ModelSelect2Multiple(url='client:languague-autocomplete'),
            'city': autocomplete.ModelSelect2(url='client:location-autocomplete'),
            'public_bio': forms.Textarea(attrs={"rows":5, "cols":20}),
            'youtube': forms.TextInput(attrs={'placeholder': '@amplypix, recommended format' }),
            'instagram': forms.TextInput(attrs={'placeholder': '@amplypix, recommended format'}),
            'tiktok': forms.TextInput(attrs={'placeholder': '@amplypix, recommended format'}),
        }

class BriefcaseForm(forms.ModelForm):

    video_url = forms.URLField()

    class Meta:
        model = Briefcase
        fields = '__all__'
        exclude = ['user']

amplypix/photographer/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
import os
from django.http import JsonResponse
import datetime
from datetime import datetime, time, date, timedelta
from django.views.generic import TemplateView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required
import urllib, json
import urllib.request
from django.contrib.contenttypes.models import ContentType
from urllib.request import Request, urlopen
from .models import *
from .forms import *
from modrator.models import User, Location
from modrator.forms import UserUpdateForm
from dal import autocomplete
# Create your views here.


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_photographer, login_url='client:index')
def complete_profile_photographer(request):

    photographer = PhotographerAP.objects.get(user=request.user)

    if request.method == 'POST':
        form = PhotographerAPForm(request.POST, request.FILES, instance=photographer)

        if form.is_valid():

            y = form.save(commit = False)
            y.save()
            form.save_m2m()
            messages.success(request, 'Your profile has been successfully updated!')
            return redirect('photographer:complete_profile_briefcase')

    else :
        form = PhotographerAPForm(instance=photographer)

    return render(request, 'photographer/index.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_photographer, login_url='client:index')
def complete_profile_briefcase(request):

    photographer = PhotographerAP.objects.get(user=request.user)

    if request.method == 'POST':
        form = BriefcaseForm(request.POST, request.FILES)

        if form.is_valid():

            y = form.save(commit = False)
            y.user = photographer
            y.save()
            messages.success(request, 'Your briefcase has been successfully updated!')
            return redirect('client:index')

    else :
        form = BriefcaseForm()

    return render(request, 'photographer/briefcase.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_photographer, login_url='client:index')
def dashboard_photographer(request):

    photographer = PhotographerAP.objects.get(user=request.user)

    return render(request, 'photographer/dashboard.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_photographer, login_url='client:index')
def update_profile_photographer(request):

    photographer = PhotographerAP.objects.get(user=request.user)
    update_complete = photographer

    if request.method == 'POST':
        form = PhotographerAPForm(request.POST, request.FILES, instance=photographer)

        if form.is_valid():

            y = form.save(commit = False)
            y.save()
            form.save_m2m()
            messages.success(request, 'Your profile has been successfully updated!')
            return redirect('photographer:dashboard_photographer')

    else :
        form = PhotographerAPForm(instance=photographer)

    return render(request, 'photographer/index.html', locals())

@login_required(redirect_field_name='/')
def profile_photographer(request, username):

    user = User.objects.get(username=username)
    photographer = PhotographerAP.objects.get(user=user)
    briefcase_ = Briefcase.objects.filter(user=photographer).first()

    return render(request, 'photographer/profile/profile.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_photographer, login_url='client:index')
def update_briefcase(request):

    photographer = PhotographerAP.objects.get(user=request.user)
    briefcase__ = Briefcase.objects.get(user=photographer)

    if request.method == 'POST':
        form = BriefcaseForm(request.POST, request.FILES, instance=briefcase__)

        if form.is_valid():

            y = form.save(commit = False)
            y.user = photographer
            y.save()
            messages.success(request, 'Your briefcase has been successfully updated!')
            return redirect('photographer:profile_photographer', request.user)

    else :
        form = BriefcaseForm(instance=briefcase__)

    return render(request, 'photographer/briefcase.html', locals())

amplypix/templates/photographer/profile/profile.html
{% extends "bases/base_dashboard.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'assets/css/dashforge.profile.css' %}">

<div class="content content-fixed content-profile">
    <div class="container pd-x-0 pd-lg-x-10 pd-xl-x-0">
      <div class="media d-block d-lg-flex">
        <div class="profile-sidebar pd-lg-r-25">
          <div class="row">
            <div class="col-sm-3 col-md-2 col-lg">
              <div class="avatar avatar-xxl avatar-online"><img src="{{ photographer.profile_picture.url }}" class="rounded-circle" alt=""></div>
            </div><!-- col -->
            <div class="col-sm-8 col-md-7 col-lg mg-t-20 mg-sm-t-0 mg-lg-t-25">
              <h5 class="mg-b-2 tx-spacing--1">{{ photographer.user.first_name }} {{ photographer.user.last_name }}</h5>
              <p class="tx-color-03 mg-b-25">{{ photographer.user }}</p>
              <div class="d-flex mg-b-25">
                <button class="btn btn-xs btn-white flex-fill">Message</button>
                <button class="btn btn-xs btn-primary flex-fill mg-l-10">Follow</button>
              </div>
  
              <p class="tx-13 tx-color-02 mg-b-25">{{ photographer.public_bio }}</p>
  
              <div class="d-flex">
                <div class="profile-skillset flex-fill">
                  <h4><a href="" class="link-01">0</a></h4>
                  <label>Stars</label>
                </div>
                <div class="profile-skillset flex-fill">
                  <h4><a href="" class="link-01">0</a></h4>
                  <label>Followers</label>
                </div>
                <div class="profile-skillset flex-fill">
                  <h4><a href="" class="link-01">0</a></h4>
                  <label>Visits</label>
                </div>
              </div>
            </div><!-- col -->
            <div class="col-sm-6 col-md-5 col-lg mg-t-40">
              <label class="tx-sans tx-10 tx-semibold tx-uppercase tx-color-01 tx-spacing-1 mg-b-15">Skills</label>
              <ul class="list-inline list-inline-skills">
                <li class="list-inline-item"><a href="">HTML5</a></li>
                <li class="list-inline-item"><a href="">Sass</a></li>
                <li class="list-inline-item"><a href="">CSS</a></li>
              </ul>
            </div><!-- col -->
            <div class="col-sm-6 col-md-5 col-lg mg-t-40">
              <label class="tx-sans tx-10 tx-semibold tx-uppercase tx-color-01 tx-spacing-1 mg-b-15">Websites &amp; Social Channel</label>
              <ul class="list-unstyled profile-info-list">
                <li><i data-feather="camera"></i> <a href="">@{{ request.user }}</a></li>
                  <li><i data-feather="twitter"></i> <a href="">{{ photographer.youtube }}</a></li>
                  <li><i data-feather="instagram"></i> <a href="">{{ photographer.instagram }}</a></li>
                  <li><i data-feather="globe"></i> <a href="">{{ photographer.tiktok }}</a></li>
              </ul>
            </div><!-- col -->
            <div class="col-sm-6 col-md-5 col-lg mg-t-40">
              <label class="tx-sans tx-10 tx-semibold tx-uppercase tx-color-01 tx-spacing-1 mg-b-15">Contact Information</label>
              <ul class="list-unstyled profile-info-list">
                <li><i data-feather="briefcase"></i> <span class="tx-color-03">{{ photographer.city }}</span></li>
                <li><i data-feather="smartphone"></i> <a href="">{{ photographer.user.phone }}</a></li>
                <li><i data-feather="calendar"></i> <a href="">{{ photographer.birth_date }}</a></li>
              </ul>
            </div><!-- col -->

          </div><!-- row -->

          
          
  
        </div><!-- profile-sidebar -->
        <div class="media-body mg-t-40 mg-lg-t-0 pd-lg-x-10">
           {% if user == request.user %}
          <div class="profile-update-option bg-white ht-50 bd d-flex justify-content-end mg-b-20 mg-lg-b-25 rounded">
            <div class="d-flex align-items-center pd-x-20 mg-r-auto">
              <i data-feather="edit-3"></i> <a href="" class="link-03 mg-l-10"><span class="d-none d-sm-inline">Share an</span> Update</a>
            </div>
            <div class="wd-50 bd-l d-flex align-items-center justify-content-center">
              <a href="" class="link-03" data-toggle="tooltip" title="Publish Photo"><i data-feather="image"></i></a>
            </div>
            <div class="wd-50 bd-l d-flex align-items-center justify-content-center">
              <a href="" class="link-03" data-toggle="tooltip" title="Publish Video"><i data-feather="video"></i></a>
            </div>
            <div class="wd-50 bd-l d-flex align-items-center justify-content-center">
              <a href="" class="link-03" data-toggle="tooltip" title="Write an Article"><i data-feather="file-text"></i></a>
            </div>
          </div>
          {% endif %}


          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message }}  </strong>
          </div>
          {% endfor %}
  
          <div class="card mg-b-20 mg-lg-b-25">
            <div class="card-header pd-y-15 pd-x-20 d-flex align-items-center justify-content-between">
              <h6 class="tx-uppercase tx-semibold mg-b-0">Latest Activity</h6>
              <nav class="nav nav-icon-only">
                <a href="" class="nav-link"><i data-feather="more-horizontal"></i></a>
              </nav>
            </div><!-- card-header -->
            <div class="card-body pd-20 pd-lg-25">
              <div class="media align-items-center mg-b-20">
                <div class="avatar avatar-online"><img src="{{ photographer.profile_picture.url }}" class="rounded-circle" alt=""></div>
                <div class="media-body pd-l-15">
                  <h6 class="mg-b-3">{{ request.user.first_name }} {{ request.user.last_name }}</h6>
                  <span class="d-block tx-13 tx-color-03">Photographer</span>
                </div>
                <span class="d-none d-sm-block tx-12 tx-color-03 align-self-start">5 hours ago</span>
              </div><!-- media -->
              <p class="mg-b-20">Our team is expanding again. We are looking for a Product Manager and Software Engineer to drive our new aspects of our capital projects. If you're interested, please drop a comment here or simply message me. <a href="">#softwareengineer</a> <a href="">#engineering</a></p>
  
              <div class="bd bg-gray-50 pd-y-15 pd-x-15 pd-sm-x-20">
                <h6 class="tx-15 mg-b-3">We're hiring of Product Manager</h6>
                <p class="mg-b-0 tx-14">Full-time, $60,000 - $80,000 annual</p>
                <span class="tx-13 tx-color-03">Bay Area, San Francisco, CA</span>
              </div>
            </div>
            <div class="card-footer bg-transparent pd-y-10 pd-sm-y-15 pd-x-10 pd-sm-x-20">
              <nav class="nav nav-with-icon tx-13">
                <a href="" class="nav-link"><i data-feather="thumbs-up"></i> Like</a>
                <a href="" class="nav-link"><i data-feather="message-square"></i> Comment</a>
                <a href="" class="nav-link"><i data-feather="share"></i> Share</a>
              </nav>
            </div><!-- card-footer -->
          </div><!-- card -->
  
          <div class="card mg-b-20 mg-lg-b-25">
            <div class="card-header pd-y-15 pd-x-20 d-flex align-items-center justify-content-between">
              <h6 class="tx-uppercase tx-semibold mg-b-0">Brief Case</h6>
              {% if request.user == photographer.user %}
              <nav class="nav nav-with-icon tx-13">
                <a href="{% url 'photographer:update_briefcase' %}" class="nav-link"><i data-feather="plus"></i> Update</a>
              </nav>
              {% endif %}
            </div><!-- card-header -->
            <div class="card-body pd-25">
              <div class="media d-block d-sm-flex">
                <a href="{{ photographer.youtube }}">
                <div class="wd-80 ht-80 bg-ui-04 rounded d-flex align-items-center justify-content-center">
                  <i data-feather="youtube" class="tx-white-7 wd-40 ht-40"></i>
                </div>
                </a>
                <div class="media-body pd-t-25 pd-sm-t-0 pd-sm-l-25">
                  <h5 class="mg-b-5">{{ photographer.youtube }}</h5>
                  <p class="mg-b-3 tx-color-02"><span class="tx-medium tx-color-01">{{ photographer.user }}.</span>, {{ photographer.city }}</p>
                  <span class="d-block tx-13 tx-color-03">{{ photographer.created_at }} - Present</span>
  
                  <ul class="pd-l-10 mg-0 mg-t-20 tx-13">
                    <li>{{ photographer.public_bio }}</li>
                  </ul>
                </div>
              </div><!-- media -->
            </div>
            
          </div><!-- card -->
          
          

        </div><!-- media-body -->
        <div class="profile-sidebar mg-t-40 mg-lg-t-0 pd-lg-l-25">
          <div class="row">
            
           
            <div class="col-sm-6 col-md-5 col-lg mg-t-40 order-sm-1">
              <div class="d-flex align-items-center justify-content-between mg-b-15">
                <h6 class="tx-13 tx-uppercase tx-semibold mg-b-0">Mutual Connections</h6>
              </div>
              <div class="img-group img-group-mutual mg-b-20 justify-content-start">
                <img src="{{ photographer.profile_picture.url }}" class="img rounded-circle" alt="">
                <img src="{{ photographer.profile_picture.url }}" class="img rounded-circle" alt="">
                <img src="{{ photographer.profile_picture.url }}" class="img rounded-circle" alt="">
                <img src="{{ photographer.profile_picture.url }}" class="img rounded-circle" alt="">
                <img src="{{ photographer.profile_picture.url }}" class="img rounded-circle" alt="">
              </div>
              <h6>You have 18 mutual connection</h6>
              <p class="tx-color-03 mg-b-0">You and Fen both know Archie Cantones, Socrates Itumay, and 17 others</p>
            </div><!-- col -->
            <div class="col-sm-6 col-md-5 col-lg mg-t-40">
              <div class="d-flex align-items-center justify-content-between mg-b-15">
                <h6 class="tx-13 tx-uppercase tx-semibold mg-b-0">Photos</h6>
                {% if request.user == photographer.user %}
                <a href="{% url 'photographer:update_briefcase' %}" class="link-03">Update Photo</a>
                {% endif %}
              </div>
  
              <div class="row row-xxs">
                <div class="col-4">
                  <a href="{{ briefcase_.photo_1.url }}" class="d-block ht-60"><img src="{{ briefcase_.photo_1.url }}" class="img-fit-cover" alt=""></a>
                </div><!-- col -->
                <div class="col-4">
                  <a href="{{ briefcase_.photo_2.url }}" class="d-block ht-60"><img src="{{ briefcase_.photo_2.url }}" class="img-fit-cover" alt=""></a>
                </div><!-- col -->
                <div class="col-4">
                  <a href="{{ briefcase_.photo_3.url }}" class="d-block ht-60"><img src="{{ briefcase_.photo_3.url }}" class="img-fit-cover" alt=""></a>
                </div><!-- col -->
                <div class="col-4 mg-t-2">
                  <a href="{{ briefcase_.photo_4.url }}" class="d-block ht-60"><img src="{{ briefcase_.photo_4.url }}" class="img-fit-cover" alt=""></a>
                </div><!-- col -->
                <div class="col-4 mg-t-2">
                  <a href="{{ briefcase_.photo_5.url }}" class="d-block ht-60"><img src="{{ briefcase_.photo_5.url }}" class="img-fit-cover" alt=""></a>
                </div><!-- col -->
              </div><!-- row -->
            </div><!-- col -->
          </div><!-- row -->
        </div><!-- profile-sidebar -->
      </div><!-- media -->
    </div><!-- container -->
  </div><!-- content -->
  


{% endblock %}