amplypix/amplypix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', include('client.urls')),   
    path('photographer/', include('photographer.urls')),


    path('modrator/', include('modrator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amplypix/client/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.views import LoginView

app_name = "client"

urlpatterns = [
    

    #index / login
    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),
    # Index Redirect Client / Photographer
    path('index', index, name='index'),


    # Complete Profile
    path('complete_profile_client', complete_profile_client, name='complete_profile_client'),
    # Dashboard Client
    path('update_profile', update_profile, name='update_profile'),
    # Profile Client
    url(r'^profile_client/(?P<username>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', profile_client, name='profile_client'),
    # Update Profile Client
    path('dashboard_client', dashboard_client, name='dashboard_client'),
    # Post Task
    path('post_task', post_task, name='post_task'),
    # Edit Task
    url(r'^edit_task/(?P<id>\d+)/$', edit_task, name='edit_task'),
    # List Task 
    path('list_task', list_task, name='list_task'),

    url(
        r'^location-autocomplete/$',
        LocationAutocomplete.as_view(),
        name='location-autocomplete',
    ),


    url(
        r'^languague-autocomplete/$',
        LanguagueAutocomplete.as_view(),
        name='languague-autocomplete',
    ),


] 

amplypix/templates/bases/base_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Twitter -->
    <meta name="twitter:site" content="@amplypix">
    <meta name="twitter:creator" content="@amplypix">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="AmplyPix">
    <meta name="twitter:description" content="Freelance Photographer">
    <meta name="twitter:image" content="https://blendgoc.com/new_assets/images/logo.png">

    <!-- Facebook -->
    <meta property="og:url" content="https://blendgoc.com">
    <meta property="og:title" content="AmplyPix">
    <meta property="og:description" content="Freelance Photographer">

    <meta property="og:image" content="https://blendgoc.com/new_assets/images/logo.png">
    <meta property="og:image:secure_url" content="https://blendgoc.com/new_assets/images/logo.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="600">

    <!-- Meta -->
    <meta name="description" content="Freelance Photographer">
    <meta name="author" content="Blendgoc">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">

    <title>AmplyPix Freelance Photographer</title>

    <!-- vendor css -->
    <link href="{% static 'assets/lib/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">

    <!-- DashForge CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/dashforge.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/dashforge.auth.css' %}">
  </head>
  <body>

    <header class="navbar navbar-header navbar-header-fixed">

      <div class="navbar-brand">
        <a href="{% url 'client:index' %}" class="df-logo">amply<span>pix</span></a>
      </div><!-- navbar-brand -->
      
      {% if request.user.is_authenticated %}
      <a href="#" id="mainMenuOpen" class="burger-menu"><i data-feather="menu"></i></a>
      
      
      <div id="navbarMenu" class="navbar-menu-wrapper">
       
        <div class="navbar-menu-header">
          <a href="{% url 'client:index' %}" class="df-logo">amply<span>pix</span></a>
          <a id="mainMenuClose" href=""><i data-feather="x"></i></a>
        </div><!-- navbar-menu-header -->
        <ul class="nav navbar-menu">
          <li class="nav-label pd-l-20 pd-lg-l-25 d-lg-none">Main Navigation</li>
          <li class="nav-item with-sub">
            <a href="" class="nav-link"><i data-feather="pie-chart"></i> Dashboard</a>
            <ul class="navbar-menu-sub">
              <li class="nav-sub-item"><a href="dashboard-one.html" class="nav-sub-link"><i data-feather="bar-chart-2"></i>Sales Monitoring</a></li>
              <li class="nav-sub-item"><a href="dashboard-two.html" class="nav-sub-link"><i data-feather="bar-chart-2"></i>Website Analytics</a></li>
              <li class="nav-sub-item"><a href="dashboard-three.html" class="nav-sub-link"><i data-feather="bar-chart-2"></i>Cryptocurrency</a></li>
              <li class="nav-sub-item"><a href="dashboard-four.html" class="nav-sub-link"><i data-feather="bar-chart-2"></i>Helpdesk Management</a></li>
            </ul>
          </li>
          <li class="nav-item with-sub">
            <a href="" class="nav-link"><i data-feather="package"></i> Apps</a>
            <ul class="navbar-menu-sub">
              <li class="nav-sub-item"><a href="app-calendar.html" class="nav-sub-link"><i data-feather="calendar"></i>Calendar</a></li>
              <li class="nav-sub-item"><a href="app-chat.html" class="nav-sub-link"><i data-feather="message-square"></i>Chat</a></li>
              <li class="nav-sub-item"><a href="app-contacts.html" class="nav-sub-link"><i data-feather="users"></i>Contacts</a></li>
              <li class="nav-sub-item"><a href="app-file-manager.html" class="nav-sub-link"><i data-feather="file-text"></i>File Manager</a></li>
              <li class="nav-sub-item"><a href="app-mail.html" class="nav-sub-link"><i data-feather="mail"></i>Mail</a></li>
            </ul>
          </li>
          <li class="nav-item with-sub">
            <a href="" class="nav-link"><i data-feather="layers"></i> Pages</a>
            <div class="navbar-menu-sub">
              <div class="d-lg-flex">
                <ul>
                  <li class="nav-label">Authentication</li>
                  <li class="nav-sub-item"><a href="page-signin.html" class="nav-sub-link"><i data-feather="log-in"></i> Sign In</a></li>
                  <li class="nav-sub-item"><a href="page-signup.html" class="nav-sub-link"><i data-feather="user-plus"></i> Sign Up</a></li>
                  <li class="nav-sub-item"><a href="page-verify.html" class="nav-sub-link"><i data-feather="user-check"></i> Verify Account</a></li>
                  <li class="nav-sub-item"><a href="page-forgot.html" class="nav-sub-link"><i data-feather="shield-off"></i> Forgot Password</a></li>
                  <li class="nav-label mg-t-20">User Pages</li>
                  <li class="nav-sub-item"><a href="page-profile-view.html" class="nav-sub-link"><i data-feather="user"></i> View Profile</a></li>
                  <li class="nav-sub-item"><a href="page-connections.html" class="nav-sub-link"><i data-feather="users"></i> Connections</a></li>
                  <li class="nav-sub-item"><a href="page-groups.html" class="nav-sub-link"><i data-feather="users"></i> Groups</a></li>
                  <li class="nav-sub-item"><a href="page-events.html" class="nav-sub-link"><i data-feather="calendar"></i> Events</a></li>
                </ul>
                <ul>
                  <li class="nav-label">Error Pages</li>
                  <li class="nav-sub-item"><a href="page-404.html" class="nav-sub-link"><i data-feather="file"></i> 404 Page Not Found</a></li>
                  <li class="nav-sub-item"><a href="page-500.html" class="nav-sub-link"><i data-feather="file"></i> 500 Internal Server</a></li>
                  <li class="nav-sub-item"><a href="page-503.html" class="nav-sub-link"><i data-feather="file"></i> 503 Service Unavailable</a></li>
                  <li class="nav-sub-item"><a href="page-505.html" class="nav-sub-link"><i data-feather="file"></i> 505 Forbidden</a></li>
                  <li class="nav-label mg-t-20">Other Pages</li>
                  <li class="nav-sub-item"><a href="page-timeline.html" class="nav-sub-link"><i data-feather="file-text"></i> Timeline</a></li>
                  <li class="nav-sub-item"><a href="page-pricing.html" class="nav-sub-link"><i data-feather="file-text"></i> Pricing</a></li>
                  <li class="nav-sub-item"><a href="page-help-center.html" class="nav-sub-link"><i data-feather="file-text"></i> Help Center</a></li>
                  <li class="nav-sub-item"><a href="page-invoice.html" class="nav-sub-link"><i data-feather="file-text"></i> Invoice</a></li>
                </ul>
              </div>
            </div><!-- nav-sub -->
          </li>
          <li class="nav-item"><a href="../../components/" class="nav-link"><i data-feather="box"></i> Components</a></li>
          <li class="nav-item"><a href="../../collections/" class="nav-link"><i data-feather="archive"></i> Collections</a></li>
        </ul>
        {% else %}

        {% endif %}
      </div><!-- navbar-menu-wrapper -->
    </header><!-- navbar -->

    {% block content %}
    <div class="content content-fixed content-auth">
      <div class="container">
        <div class="media align-items-stretch justify-content-center ht-100p pos-relative">
          <div class="media-body align-items-center d-none d-lg-flex">
            <div class="mx-wd-600">
              <img src="{% static 'assets/img/img15.png' %}" class="img-fluid" alt="">
            </div>
          </div><!-- media-body -->
          <div class="sign-wrapper mg-lg-r-50 mg-xl-l-60">
            <div class="wd-100p">
              <h3 class="tx-color-01 mg-b-5">Sign In</h3>
              <p class="tx-color-03 tx-16 mg-b-40">Welcome back! Please signin to continue.</p>

              
              <div class="form-group">
                <label>Email address</label>
                <input type="email" class="form-control" placeholder="yourname@yourmail.com">
              </div>
              <div class="form-group">
                <div class="d-flex justify-content-between mg-b-5">
                  <label class="mg-b-0-f">Password</label>
                  <a href="" class="tx-13">Forgot password?</a>
                </div> 
                <input type="password" class="form-control" placeholder="Enter your password">
              </div>
              <button class="btn btn-brand-02 btn-block">Sign In</button>
              <div class="divider-text">or</div>
              <button class="btn btn-outline-facebook btn-block">Sign In With Facebook</button>
              <button class="btn btn-outline-twitter btn-block">Sign In With Twitter</button>
              
              <div class="tx-13 mg-t-20 tx-center">Don't have an account? <a href="{% url 'modrator:signup_users' %}">Create an Account</a></div>
            </div>
          </div><!-- sign-wrapper -->
        </div><!-- media -->
      </div><!-- container -->
    </div><!-- content -->
    {% endblock %}

    <footer class="footer">
      <div>
        <span>&copy; 2020 AmplyPix v1.0.0. </span>
        <span>Created by <a href="https://blendgoc.com">BlendGoc</a></span>
      </div>
      <div>
        <nav class="nav">
          <a href="#" class="nav-link">Get Help</a>
        </nav>
      </div>
    </footer>

    <script src="{% static 'assets/lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/lib/feather-icons/feather.min.js' %}"></script>
    <script src="{% static 'assets/lib/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>

    <script src="{% static 'assets/js/dashforge.js' %}"></script>

    <!-- append theme customizer -->
    <script src="{% static 'assets/lib/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'assets/js/dashforge.settings.js' %}"></script>

    
  </body>
</html>